### ISSUE TITLE
AdditionalProperties not accepted by the current CRD Validation Spec

### ISSUE THREAD

**Issue by tamalsaha** [ant31/crd-validation#2]
Hi,
Thanks for this handy library. One question I have is why do you think `additionalProperties` field is not supported by Kubernetes ? This field seems to be present in Go type and present in [kubernetes/kube-openapi](https://github.com/kubernetes/kube-openapi/search?utf8=%E2%9C%93&q=additionalProperties&type=) tests.

https://github.com/ant31/crd-validation/blob/eabcf70a1bd73e9296fa0c5f57de604689200a1b/pkg/convert_types.go#L120

**Comment by tamalsaha** [comment]
I filed a pr to fix the issue https://github.com/kubernetes/kubernetes/pull/61991

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/kubernetes/issues/59485

**Comment by tamalsaha** [comment]
Fixed in upstream
